<a href="https://colab.research.google.com/github/vecha2468/CMPE_255_GROUP_11/blob/main/DataMining_Project_Group_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import auth
auth.authenticate_user()

Import Core Libraries

In [4]:
!pip install pandas-gbq

Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.12/dist-packages (0.30.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (75.2.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.4.4)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.0.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.2.2)
Requirement already satisfied: pyarrow>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (18.1.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.10.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.28.1)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.38.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.2.3)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.4.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (3.38.0)
Requirement already satisfied: packaging>=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (25.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.72.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.26.1)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.32.4)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.71.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.7.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2025.11.12)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (4.15.0)

In [5]:
!pip install sodapy
import pandas as pd
from sodapy import Socrata

Collecting sodapy
  Downloading sodapy-2.2.0-py2.py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: requests>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from sodapy) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.1->sodapy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.1->sodapy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.1->sodapy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.1->sodapy) (2025.11.12)
Downloading sodapy-2.2.0-py2.py3-none-any.whl (15 kB)
Installing collected packages: sodapy
Successfully installed sodapy-2.2.0

In [6]:
import os
import pandas as pd
import numpy as np
import warnings
import matplotlib.pyplot as plt

from sodapy import Socrata
warnings.filterwarnings('ignore')

In [7]:
domain = "data.cdc.gov"
client = Socrata(domain, None)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [8]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

COVID Dataset

In [9]:
# https://data.cdc.gov/resource/pwn4-m3yp.json
# Enter the information from those sections here

covid_dataset_identifier = 'pwn4-m3yp'
covid_results = client.get(covid_dataset_identifier)
covid_df = pd.DataFrame.from_dict(covid_results)

In [10]:
to_drop=['start_date','end_date','new_historic_cases','new_historic_deaths','tot_cases']

covid_df.drop(to_drop,inplace=True,axis=1)

In [11]:
covid_df['Disease']='Covid'
covid_df = covid_df.rename(columns={'date_updated': 'Date'})
covid_df['Date']=pd.to_datetime(covid_df['Date'])
covid_df = covid_df.sort_values(by=['Date'])
covid_df = covid_df.rename(columns={'state':'State'})
covid_df = covid_df.rename(columns={'tot_deaths':'covid_19_deaths', 'new_deaths':'New_Deaths'})
covid_df['year']=covid_df['Date'].dt.year
covid_df=covid_df[['year','State','covid_19_deaths']]

In [12]:
covid_df=covid_df[covid_df.covid_19_deaths.astype(float)>0]

State=['CA', 'AZ', 'AR', 'AL', 'AK', 'AS', 'KS', 'NYC', 'DC', 'OK', 'LA',
       'VA', 'GA', 'NV', 'IL', 'FL']

full_names={'CA':'California', 'AZ':'Arizona', 'AR':'Arkansas', 'AL':'Alabama', 'AK':'Alaska', 'AS': 'Arkansas', 'KS':'Kansas', 'NYC':'New York City',
            'DC':'District of Columbia', 'OK':'Oklahoma', 'LA':'Louisiana','VA':'Virginia', 'GA':'Georgia', 'NV':'Nevada', 'IL':'Illinois', 'FL':'Florida'}


covid_df['State']=covid_df['State'].replace(full_names)
covid_df.head()

     year       State covid_19_deaths
870  2020  California             1.0
871  2020  California             3.0
872  2020  California            15.0
353  2020    Arkansas             3.0
62   2020      Alaska             1.0

In [13]:
dis1_dataset_identifier = '9dzk-mvmi'
dis1_results = client.get(dis1_dataset_identifier)
dis1_df = pd.DataFrame.from_dict(dis1_results)

columns1=['data_as_of','start_date','end_date','flag_accid','flag_mva','flag_suic','flag_homic','flag_drugod','natural_cause','accidents_unintentional','motor_vehicle_accidents',
          'intentional_self_harm_suicide','assault_homicide','assault_homicide','all_cause','septicemia','chronic_lower_respiratory','symptoms_signs_and_abnormal','drug_overdose',
              'covid_19_multiple_cause_of','covid_19_underlying_cause','month']

dis1_df.drop(columns1,inplace=True,axis=1)
dis1_df=dis1_df.rename(columns={'jurisdiction_of_occurrence':'State'})


dis1_df.head()

,State,year,malignant_neoplasms,diabetes_mellitus,alzheimer_disease,influenza_and_pneumonia,other_diseases_of_respiratory,nephritis_nephrotic_syndrome,diseases_of_heart,cerebrovascular_diseases
0,United States,2020,52635,8234,11122,6656,4497,4886,60896,14113
1,United States,2020,48764,7766,10444,6147,4067,4507,56851,12818
2,United States,2020,51640,8433,11385,7579,4499,4727,60229,13742
3,United States,2020,48773,9440,12307,5781,4026,4476,62285,13420
4,United States,2020,49012,8361,10706,3612,3489,4122,56561,12776

In [14]:
dis2_dataset_identifier = '65mz-jvh5'
dis2_results = client.get(dis2_dataset_identifier)
dis2_df = pd.DataFrame.from_dict(dis2_results)

columns2=['analysisdate','date_of_death_month','start_date','end_date','race_ethnicity','naturalcause','septicemia_a40_a41','allcause',
          'chronic_lower_respiratory','symptoms_signs_and_abnormal','covid_19_u071_underlying','covid_19_u071_multiple_cause']

dis2_df.drop(columns2,inplace=True,axis=1)
dis2_df=dis2_df.rename(columns={'malignant_neoplasms_c00_c97':'malignant_neoplasms','diabetes_mellitus_e10_e14':'diabetes_mellitus','alzheimer_disease_g30':'alzheimer_disease',
                                            'influenza_and_pneumonia_j09':'influenza_and_pneumonia','diseases_of_heart_i00_i09':'diseases_of_heart',
                                            'covid_19_u071_multiple_cause':'covid_19_multiple_cause_of','date_of_death_year':'year','jurisdiction_of_occurrence':'State'})
dis2_df.head()

,year,State,sex,agegroup,malignant_neoplasms,diabetes_mellitus,alzheimer_disease,influenza_and_pneumonia,other_diseases_of_respiratory,nephritis_nephrotic_syndrome,diseases_of_heart,cerebrovascular_diseases
0,2019,United States,M,0-4 years,1,0,0,1,1,0,0,1
1,2019,United States,F,25-34 years,1,0,0,0,0,0,1,1
2,2020,United States,Female,0-4 years,0,0,0,1,0,0,0,0
3,2020,United States,Female,5-14 years,0,0,0,1,0,0,0,0
4,2020,United States,Female,15-24 years,0,0,0,0,0,0,0,0

In [15]:
dis3_dataset_identifier = 'muzy-jte6'
dis3_results = client.get(dis3_dataset_identifier)
dis3_df = pd.DataFrame.from_dict(dis3_results)



columns3=['data_as_of','mmwrweek','week_ending_date','natural_cause','flag_cov19mcod','flag_cov19ucod','flag_otherresp',
          'flag_sept','flag_otherunk','flag_inflpn','flag_diab','flag_nephr','flag_alz','flag_clrd','flag_stroke','flag_hd','flag_neopl',
          'septicemia_a40_a41','all_cause','chronic_lower_respiratory','symptoms_signs_and_abnormal','covid_19_u071_underlying_cause_of_death',
              'covid_19_u071_multiple_cause_of_death']

dis3_df.drop(columns3,inplace=True,axis=1)


dis3_df=dis3_df.rename(columns={'malignant_neoplasms_c00_c97':'malignant_neoplasms','diabetes_mellitus_e10_e14':'diabetes_mellitus','alzheimer_disease_g30':'alzheimer_disease',
                                            'influenza_and_pneumonia_j09_j18':'influenza_and_pneumonia','diseases_of_heart_i00_i09':'diseases_of_heart',
                                'jurisdiction_of_occurrence':'State','mmwryear':'year'})


dis3_df.head()

,State,year,malignant_neoplasms,diabetes_mellitus,alzheimer_disease,influenza_and_pneumonia,other_diseases_of_respiratory,nephritis_nephrotic_syndrome,diseases_of_heart,cerebrovascular_diseases
0,United States,2020,11567,1829,2537,1559,1068,1094,14204,3110
1,United States,2020,11963,1942,2566,1528,1035,1092,13911,3189
2,United States,2020,11701,1819,2491,1484,992,1121,13593,3256
3,United States,2020,11879,1864,2517,1488,979,1107,13612,3185
4,United States,2020,11963,1828,2480,1411,981,1074,13465,3084

In [16]:
dis4_dataset_identifier = 'ezfr-g6hf'
dis4_results = client.get(dis4_dataset_identifier)
dis4_df = pd.DataFrame.from_dict(dis4_results)
dis4_df.head()


columns4=['date_of_death_month','hhsregion','naturalcause','analysisdate','flag_diab','flag_clrd','flag_stroke',
          'flag_nephr','diabetes_mellitus_e10_e14','flag_sept','note','flag_inflpn','flag_otherunk','flag_otherresp','flag_alz','flag_neopl','flag_hd',
          'flag_cov19mcod','flag_cov19ucod','flag_natcause','flag_allcause','allcause','septicemia_a40_a41','symptoms_signs_and_abnormal',
          'covid_19_u071_multiple_cause','covid_19_u071_underlying','chronic_lower_respiratory']

dis4_df.drop(columns4,inplace=True,axis=1)

dis4_df=dis4_df.rename(columns={'malignant_neoplasms_c00_c97':'malignant_neoplasms','diabetes_mellitus_e10_e14':'diabetes_mellitus','alzheimer_disease_g30':'alzheimer_disease',
                                            'influenza_and_pneumonia_j09':'influenza_and_pneumonia','diseases_of_heart_i00_i09':'diseases_of_heart',
                                            'covid_19_u071_multiple_cause':'covid_19_multiple_cause_of','date_of_death_year':'year','jurisdiction_of_occurrence':'State'})

dis4_df.head()

,year,agegroup,malignant_neoplasms,alzheimer_disease,influenza_and_pneumonia,other_diseases_of_respiratory,diseases_of_heart,nephritis_nephrotic_syndrome,cerebrovascular_diseases
0,2019,0-4 years,23,0,31,27,34,NaN,NaN
1,2021,85 years and over,397,228,54,66,970,63,185
2,2019,15-24 years,123,0,18,14,71,NaN,18
3,2019,25-34 years,268,0,55,29,285,27,46
4,2019,35-44 years,955,0,120,53,886,70,131

In [17]:
dis5_dataset_identifier = 'ynw2-4viq'
dis5_results = client.get(dis5_dataset_identifier)
dis5_df = pd.DataFrame.from_dict(dis5_results)

columns5=['data_as_of','start_week','end_week','mmwrweek','week_ending_date','group','indicator','footnote','total_deaths']

dis5_df.drop(columns5,inplace=True,axis=1)
dis5_df=dis5_df.rename(columns={'mmwryear':'year','jurisdiction':'State'})

#dis5_df=dis5_df[dis5_df.covid_19_deaths.astype(float)>0]

dis5_df.head()

,year,State,age_group,covid_19_deaths,pneumonia_deaths,influenza_deaths,pneumonia_or_influenza,pneumonia_influenza_or_covid
0,2020,United States,All Ages,0,4102,432,4534,4534
1,2020,United States,0-17 years,0,19,22,41,41
2,2020,United States,18-64 years,0,767,183,950,950
3,2020,United States,65 years and over,0,3316,227,3543,3543
4,2023,HHS Region 6,0-17 years,0,0,0,0,0

In [18]:
dis6_dataset_identifier = '9bhg-hcku'
dis6_results = client.get(dis6_dataset_identifier)
dis6_df = pd.DataFrame.from_dict(dis6_results)
dis6_df['start_date'] =pd.to_datetime(dis6_df['start_date']).dt.date
columns6=['data_as_of','end_date','group','total_deaths','footnote','pneumonia_and_covid_19_deaths']

dis6_df.drop(columns6,inplace=True,axis=1)
dis6_df=dis6_df.rename(columns={'start_date':'date','state':'State'})

dis6_df.head()

,date,State,sex,age_group,covid_19_deaths,pneumonia_deaths,influenza_deaths,pneumonia_influenza_or_covid
0,2020-01-01,United States,All Sexes,All Ages,1146774,1162844,22229,1760095
1,2020-01-01,United States,All Sexes,Under 1 year,519,1056,64,1541
2,2020-01-01,United States,All Sexes,0-17 years,1696,2961,509,4716
3,2020-01-01,United States,All Sexes,1-4 years,285,692,177,1079
4,2020-01-01,United States,All Sexes,5-14 years,509,818,219,1390

In [19]:
covid19_df=pd.DataFrame.from_dict(dis5_results)
covid19_df['start_week'] =pd.to_datetime(covid19_df['start_week']).dt.date
columns19=['data_as_of','mmwryear','end_week','mmwrweek','week_ending_date','group','indicator','footnote','total_deaths']
covid19_df.drop(columns19,inplace=True,axis=1)
covid19_df=covid19_df.rename(columns={'start_week':'date','jurisdiction':'State'})


merged_df_cip=pd.merge(covid19_df,dis6_df,how='outer')
merged_df_cip=merged_df_cip.fillna(0)
merged_df_cip=merged_df_cip[merged_df_cip.covid_19_deaths.astype(int)>0]
merged_df_cip.head()

,date,State,age_group,covid_19_deaths,pneumonia_deaths,influenza_deaths,pneumonia_or_influenza,pneumonia_influenza_or_covid,sex
252,2020-01-01,Alabama,0-17 years,10,20,0,0,33,Male
253,2020-01-01,Alabama,0-17 years,19,45,0,0,67,All Sexes
258,2020-01-01,Alabama,15-24 years,21,24,0,0,40,Female
259,2020-01-01,Alabama,15-24 years,25,27,0,0,45,Male
260,2020-01-01,Alabama,15-24 years,46,51,0,0,85,All Sexes

In [20]:
final_merged_df1=pd.concat([covid_df,dis5_df])

final_merged_df1=final_merged_df1.dropna()


#final_merged_df1=final_merged_df1[final_merged_df1.covid_19_deaths.astype(int)>0]


final_merged_df1.head()

,year,State,covid_19_deaths,age_group,pneumonia_deaths,influenza_deaths,pneumonia_or_influenza,pneumonia_influenza_or_covid
0,2020,United States,0,All Ages,4102,432,4534,4534
1,2020,United States,0,0-17 years,19,22,41,41
2,2020,United States,0,18-64 years,767,183,950,950
3,2020,United States,0,65 years and over,3316,227,3543,3543
4,2023,HHS Region 6,0,0-17 years,0,0,0,0

In [21]:
merged_all_df1=pd.merge(dis1_df,dis3_df,how='outer')
merged_all_df1.dropna()

merged_all_df1.head()

,State,year,malignant_neoplasms,diabetes_mellitus,alzheimer_disease,influenza_and_pneumonia,other_diseases_of_respiratory,nephritis_nephrotic_syndrome,diseases_of_heart,cerebrovascular_diseases
0,Alabama,2020,144,25,65,34,24,23,265,57
1,Alabama,2020,157,16,58,31,17,20,265,55
2,Alabama,2020,161,29,53,21,14,15,241,47
3,Alabama,2020,166,26,60,20,21,15,291,74
4,Alabama,2020,166,31,63,18,20,17,265,64

In [22]:
merged_all_df2=pd.merge(dis2_df,dis4_df,how='outer')
merged_all_df2.dropna()
merged_all_df2.head()

,year,State,sex,agegroup,malignant_neoplasms,diabetes_mellitus,alzheimer_disease,influenza_and_pneumonia,other_diseases_of_respiratory,nephritis_nephrotic_syndrome,diseases_of_heart,cerebrovascular_diseases
0,2019,United States,F,0-4 years,0,0,0,0,0,0,0,0
1,2019,United States,F,0-4 years,0,0,0,0,0,0,0,0
2,2019,United States,F,0-4 years,0,0,0,0,0,0,0,0
3,2019,United States,M,0-4 years,0,0,0,0,0,0,0,0
4,2019,United States,M,0-4 years,0,0,0,0,0,0,0,0

In [23]:
final_merged_df2=pd.merge(merged_all_df1,merged_all_df2,how='outer')
final_merged_df2.dropna(subset=['sex','agegroup'],inplace=True)

mapping={'M':'Male','F':'Female'}

final_merged_df2['sex']=final_merged_df2['sex'].replace(mapping)


final_merged_df2.head()

,State,year,malignant_neoplasms,diabetes_mellitus,alzheimer_disease,influenza_and_pneumonia,other_diseases_of_respiratory,nephritis_nephrotic_syndrome,diseases_of_heart,cerebrovascular_diseases,sex,agegroup
806,United States,2019,0,0,0,0,0,0,0,0,Female,0-4 years
807,United States,2019,0,0,0,0,0,0,0,0,Female,0-4 years
808,United States,2019,0,0,0,0,0,0,0,0,Female,0-4 years
809,United States,2019,0,0,0,0,0,0,0,0,Male,0-4 years
810,United States,2019,0,0,0,0,0,0,0,0,Male,0-4 years

In [24]:
final_merged_df1.info()
final_merged_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   year                          365 non-null    object
 1   State                         365 non-null    object
 2   covid_19_deaths               365 non-null    object
 3   age_group                     365 non-null    object
 4   pneumonia_deaths              365 non-null    object
 5   influenza_deaths              365 non-null    object
 6   pneumonia_or_influenza        365 non-null    object
 7   pneumonia_influenza_or_covid  365 non-null    object
dtypes: object(8)
memory usage: 33.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 806 to 1870
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   State                          1000 non-null   object
 1   year                           1000 non-null   object
 2   malignant_neoplasms            1000 non-null   object
 3   diabetes_mellitus              1000 non-null   object
 4   alzheimer_disease              1000 non-null   object
 5   influenza_and_pneumonia        1000 non-null   object
 6   other_diseases_of_respiratory  1000 non-null   object
 7   nephritis_nephrotic_syndrome   1000 non-null   object
 8   diseases_of_heart              1000 non-null   object
 9   cerebrovascular_diseases       1000 non-null   object
 10  sex                            1000 non-null   object
 11  agegroup                       1000 non-null   object
dtypes: object(12)
memory usage: 133.9+ KB