<a href="https://colab.research.google.com/github/vecha2468/CMPE_255_GROUP_11/blob/main/DataMining_Project_Group_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
from google.colab import auth
auth.authenticate_user()

Import Core Libraries

In [76]:
!pip install pandas-gbq

Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.12/dist-packages (0.30.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (75.2.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.4.4)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.0.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.2.2)
Requirement already satisfied: pyarrow>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (18.1.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: google-api-core<3.0.0,>=2.10.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.28.1)
Requirement already satisfied: google-auth>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.38.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.2.3)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.4.2 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (3.38.0)
Requirement already satisfied: packaging>=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (25.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.72.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (1.26.1)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.32.4)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.13.0->pandas-gbq) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->pandas-gbq) (2025.2)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.71.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.7.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core<3.0.0,>=2.10.2->pandas-gbq) (2025.11.12)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4.0.0,>=3.4.2->pandas-gbq) (4.15.0)

In [77]:
!pip install sodapy
import pandas as pd
from sodapy import Socrata

Requirement already satisfied: sodapy in /usr/local/lib/python3.12/dist-packages (2.2.0)
Requirement already satisfied: requests>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from sodapy) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.1->sodapy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.1->sodapy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.1->sodapy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.28.1->sodapy) (2025.11.12)

In [78]:
import os
import pandas as pd
import numpy as np
import warnings
import matplotlib.pyplot as plt

from sodapy import Socrata
warnings.filterwarnings('ignore')

In [79]:
domain = "data.cdc.gov"
client = Socrata(domain, None)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [80]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

COVID Dataset

In [82]:
# https://data.cdc.gov/resource/pwn4-m3yp.json
# Enter the information from those sections here

covid_dataset_identifier = 'pwn4-m3yp'
covid_results = client.get(covid_dataset_identifier)
covid_df = pd.DataFrame.from_dict(covid_results)

In [83]:
to_drop=['start_date','end_date','new_historic_cases','new_historic_deaths','tot_cases']

covid_df.drop(to_drop,inplace=True,axis=1)

In [84]:
covid_df['Disease']='Covid'
covid_df = covid_df.rename(columns={'date_updated': 'Date'})
covid_df['Date']=pd.to_datetime(covid_df['Date'])
covid_df = covid_df.sort_values(by=['Date'])
covid_df = covid_df.rename(columns={'state':'State'})
covid_df = covid_df.rename(columns={'tot_deaths':'covid_19_deaths', 'new_deaths':'New_Deaths'})
covid_df['year']=covid_df['Date'].dt.year
covid_df=covid_df[['year','State','covid_19_deaths']]

In [85]:
covid_df=covid_df[covid_df.covid_19_deaths.astype(float)>0]

State=['CA', 'AZ', 'AR', 'AL', 'AK', 'AS', 'KS', 'NYC', 'DC', 'OK', 'LA',
       'VA', 'GA', 'NV', 'IL', 'FL']

full_names={'CA':'California', 'AZ':'Arizona', 'AR':'Arkansas', 'AL':'Alabama', 'AK':'Alaska', 'AS': 'Arkansas', 'KS':'Kansas', 'NYC':'New York City',
            'DC':'District of Columbia', 'OK':'Oklahoma', 'LA':'Louisiana','VA':'Virginia', 'GA':'Georgia', 'NV':'Nevada', 'IL':'Illinois', 'FL':'Florida'}


covid_df['State']=covid_df['State'].replace(full_names)
covid_df.head()

     year       State covid_19_deaths
870  2020  California             1.0
871  2020  California             3.0
872  2020  California            15.0
353  2020    Arkansas             3.0
62   2020      Alaska             1.0

In [86]:
dis1_dataset_identifier = '9dzk-mvmi'
dis1_results = client.get(dis1_dataset_identifier)
dis1_df = pd.DataFrame.from_dict(dis1_results)

columns1=['data_as_of','start_date','end_date','flag_accid','flag_mva','flag_suic','flag_homic','flag_drugod','natural_cause','accidents_unintentional','motor_vehicle_accidents',
          'intentional_self_harm_suicide','assault_homicide','assault_homicide','all_cause','septicemia','chronic_lower_respiratory','symptoms_signs_and_abnormal','drug_overdose',
              'covid_19_multiple_cause_of','covid_19_underlying_cause','month']

dis1_df.drop(columns1,inplace=True,axis=1)
dis1_df=dis1_df.rename(columns={'jurisdiction_of_occurrence':'State'})


dis1_df.head()

,State,year,malignant_neoplasms,diabetes_mellitus,alzheimer_disease,influenza_and_pneumonia,other_diseases_of_respiratory,nephritis_nephrotic_syndrome,diseases_of_heart,cerebrovascular_diseases
0,United States,2020,52635,8234,11122,6656,4497,4886,60896,14113
1,United States,2020,48764,7766,10444,6147,4067,4507,56851,12818
2,United States,2020,51640,8433,11385,7579,4499,4727,60229,13742
3,United States,2020,48773,9440,12307,5781,4026,4476,62285,13420
4,United States,2020,49012,8361,10706,3612,3489,4122,56561,12776